services:
  app:
    image: node:19-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
      - 24678:24678
    working_dir: /app
    networks:
      - eganet
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - eganet
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - eganet
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
    eganet:
        driver: bridge
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local